#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [1]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [2]:
b=np.array([int(x==4) for x in range(10)])
print(b)

[0 0 0 0 1 0 0 0 0 0]


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
import numpy as np
a = np.arange(15,55)
a

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54])

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [6]:
np.random.normal(0, 9, (3, 3))

array([[ -1.08633758,   1.46610651,   0.87277038],
       [  7.2051031 ,   6.50205473,   5.4099458 ],
       [  8.53879209, -19.37348882,  -2.65157399]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [8]:
a = [1,2,0,0,4,0]
b = np.nonzero(a)
print(np.array(b).ndim)
print(b)

2
(array([0, 1, 4], dtype=int64),)


#### 7. Create a 3x3 identity matrix (★☆☆)

In [9]:
# method1
a= np.identity(3)
Print(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# method2
a = np.eye(3, M=None, k=1,like=None)
print(a)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [12]:
a= np.random.random((3,3,3))
print(a)

[[[0.70273305 0.24262961 0.44703231]
  [0.89967948 0.17459598 0.59648182]
  [0.81523941 0.08676126 0.41979967]]

 [[0.55887086 0.36184817 0.22576693]
  [0.82440373 0.85865278 0.66759809]
  [0.94768842 0.71254744 0.17034631]]

 [[0.37681749 0.70061928 0.62635408]
  [0.73352412 0.96375083 0.6156639 ]
  [0.31255754 0.92753412 0.83101862]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
a = np.random.random ((10,10))
print(a)
a_max,a_min = a.max(),a.min()
print("Maximim and Minimum are :")
print(a_max,a_min)

[[2.30875660e-01 1.31063951e-01 8.03769988e-02 6.06039868e-01
  6.66704481e-01 9.92380919e-01 3.72937967e-01 6.62547780e-01
  8.23432440e-01 9.18499140e-01]
 [3.35355982e-01 3.92386446e-01 9.92140611e-01 4.44032575e-01
  9.02674066e-01 4.90525846e-01 8.02544599e-01 2.11628767e-02
  3.06608779e-01 3.34670391e-01]
 [6.84596091e-01 2.24564052e-01 3.69230861e-02 8.67210589e-01
  8.36708760e-01 3.40846994e-01 4.72389707e-01 9.81221604e-01
  6.11626063e-01 7.35263729e-01]
 [8.57090019e-01 3.62723624e-01 4.11126067e-01 5.98753786e-01
  4.23443191e-01 8.05992722e-01 2.22851341e-01 3.60969767e-01
  7.55080434e-01 1.85210896e-01]
 [4.86543353e-01 4.77284349e-01 7.08022433e-01 1.98351618e-01
  2.37293581e-01 8.76391297e-01 8.07193521e-01 6.62325242e-01
  1.91362738e-01 7.13197474e-01]
 [3.32888608e-01 4.67078097e-01 8.92269891e-01 2.28702602e-01
  8.17590288e-01 7.34939730e-01 1.77416541e-01 5.72616798e-04
  5.01835866e-02 3.24532700e-01]
 [3.06280918e-03 8.48402855e-01 1.24390652e-01 8.86234060e

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
a =np.random.random(30)
print(a)
b= np.mean(a)
print(b)

[0.44302451 0.38237061 0.90788786 0.02675231 0.92060787 0.93619018
 0.48240019 0.73159817 0.05374452 0.34101182 0.44718697 0.94841763
 0.66121725 0.68037149 0.24539735 0.24665759 0.05256084 0.06465565
 0.61551996 0.52816261 0.98100693 0.26069214 0.75815062 0.0193978
 0.97646169 0.42247191 0.55016935 0.49146551 0.93409315 0.19971063]
0.5103118365770271


#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [45]:
b = np.diag(1+ np.arange(4),k=-1)
print(b)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)

In [47]:
a = np.random.random ((5,5))
print(a)
b= np.mean(a)
c= (a - b)/np.std(a)
print("After normalization:")
print(b)

[[0.87190515 0.33601173 0.32915803 0.03558161 0.27819068]
 [0.55470564 0.65904442 0.71623475 0.5785306  0.34914701]
 [0.35907764 0.78523211 0.72357044 0.13059958 0.40006759]
 [0.65279316 0.92003729 0.09166663 0.1761951  0.78027518]
 [0.68268746 0.40223053 0.3183446  0.73949682 0.38876606]]
After normalization:
0.4903819925369891


#### 13. How to find common values between two arrays? (★☆☆)

In [49]:
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a)
print(b)
print(np.intersect1d(a,b))

[9 5 3 5 7 4 2 9 5 3]
[4 0 6 3 9 0 4 8 7 0]
[3 4 7 9]


#### 14. Create a random vector of size 10 and sort it (★★☆)

In [55]:
a = np.random.random(10)
a.sort()
print(a)

[0.0391642  0.17143412 0.31022359 0.34177112 0.45804299 0.62400238
 0.77126318 0.78689133 0.79344287 0.84454053]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [58]:
a = np.random.random(10)
print(a)
a[a.argmax()]= 0
print(a)

[0.53866547 0.70439314 0.46548405 0.14670463 0.63018722 0.81242069
 0.79205703 0.35627634 0.12255757 0.26282182]
[0.53866547 0.70439314 0.46548405 0.14670463 0.63018722 0.
 0.79205703 0.35627634 0.12255757 0.26282182]


#### 16. Subtract the mean of each row of a matrix (★★☆)

In [77]:
a = np.random.random((5,5))
b = a - a.mean(axis=1, keepdims= True)
print(b)

[[ 0.06466681 -0.61229377 -0.10084466  0.28602948  0.36244215]
 [ 0.21419557 -0.01097097  0.38734434 -0.4722331  -0.11833585]
 [-0.29709807 -0.19927503  0.36368964  0.32646291 -0.19377944]
 [-0.42640298 -0.00995043 -0.03370917  0.15647609  0.31358648]
 [ 0.00574643  0.32669797 -0.16405641 -0.12445567 -0.04393232]]


#### 17. How to get the n largest values of an array (★★★)

In [84]:
a = np.arange(10000)
np.random.shuffle(a)
print(b)


None


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 