In [1]:
A = [[0.0144, 0.0336, 0.0528], 
    [0.0336, 0.1600, 0.2200],
     [0.0528,0.2200, 1.2100]]

In [2]:
A

[[0.0144, 0.0336, 0.0528], [0.0336, 0.16, 0.22], [0.0528, 0.22, 1.21]]

In [3]:
import numpy as np

A = np.array([[0.0144, 0.0336, 0.0528],
              [0.0336, 0.1600, 0.2200],
              [0.0528, 0.2200, 1.2100]])

A_inv = np.linalg.inv(A)

print(A_inv)


[[137.06140351 -27.4122807   -0.99681021]
 [-27.4122807   13.81578947  -1.31578947]
 [ -0.99681021  -1.31578947   1.1091779 ]]


In [4]:
B = [0.05,0.2, 0.5]

In [5]:
optimal = A_inv * B 

In [6]:
optimal

array([[ 6.85307018, -5.48245614, -0.4984051 ],
       [-1.37061404,  2.76315789, -0.65789474],
       [-0.04984051, -0.26315789,  0.55458895]])

In [7]:
import numpy as np

# Define matrix A and vector B
A = np.array([[0.0144, 0.0336, 0.0528],
              [0.0336, 0.1600, 0.2200],
              [0.0528, 0.2200, 1.2100]])

B = np.array([0.05, 0.2, 0.5])

# Calculate the inverse of matrix A
A_inv = np.linalg.inv(A)

# Compute the product of A_inv and B
result = A_inv.dot(B)

print(result)


[0.87220893 0.73464912 0.24159055]
